import { Header } from "./components/header/header";
import { Menu } from "./components/menu/menu";
import { Cart } from "./components/cart/cart";
import { FloatingCTAs } from "./components/floating-ctas/floating-ctas";
import type { Metadata } from "next";
import "./globals.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>{children}</main>
        <Menu />
        <Cart />
        <FloatingCTAs />
      </body>
    </html>
  );
}
